name: Generate terraform docs

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md


jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Render terraform docs and push changes back
        uses: terraform-docs/gh-actions@main
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"
