name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
  pull_request:


jobs:
  show-context:
    runs-on: ubuntu-latest
    steps:
      - name: Show github context object
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}

  test:
    strategy:
      matrix:
        runs-on:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        terraform:
          - 1.4.0
          - latest
    runs-on: ${{ matrix.runs-on }}
    env:
      TF_LOG_PROVIDER: debug
      TF_PLATFORM: ${{ matrix.runs-on }}
      TF_VERSION: ${{ matrix.terraform}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup tools
        uses: ./.github/actions/setup-tools
        with:
          terraform-version: ${{ matrix.terraform }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Run test
        run: go test -timeout 0
        working-directory: tests
